// <auto-generated />
namespace BMSEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class date_time_added_in_userBook_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_time_added_in_userBook_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202107111132191_date_time_added_in_userBook_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
