// <auto-generated />
namespace BMSEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class status_in_book_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(status_in_book_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202106201554063_status_in_book_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
