// <auto-generated />
namespace BMSEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MFollowUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MFollowUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070836308_MFollowUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
